server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
  cloud:
    config:
      server:
        git: #default
          uri: http://github.com/joneconsulting/spring-cloud-config
          default-label: master
        native:
          search-locations: file://${user.home}/Desktop/git-config-file
  profiles:
    active: native
management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh
